ipfs/helia-verified-fetch

- packages/verified-fetch/src/utils/dag-cbor-to-safe-json.ts
- packages/verified-fetch/test/accept-header.spec.ts
Removes the CID decoder and disallows `undefined` when decoding CBOR as these do not round-trip to JSON.
Expands the test suite to be explicit about the types that are not supported.
> fix: do not coerce `undefined` to `null` for JSON serialization

- packages/verified-fetch/test/accept-header.spec.ts
This module supports retrieving raw IPNS records so the test for this can be unskipped.
> chore: unskip IPNS test

- packages/verified-fetch/src/utils/parse-url-string.ts
- packages/verified-fetch/test/utils/parse-url-string.spec.ts
Adds support for fetching resources in the form:
- IPFS Path, e.g. `/ipfs/<CID>`
- IPNS Path, e.g. `/ipns/<PeerId>`
- IPFS Gateway Path, e.g. `http://example.com/ipfs/<CID>`
- IPNS Gateway Path, e.g. `http://example.com/ipns/<PeerId>`
- IPFS Subdomain Gateway Path, e.g. `http://<CID>.ipfs.example.com`
- IPNS Subdomain Gateway Path, e.g. `http://<PeerId>.ipns.example.com`
Notes:
- Supports paths & queries as per `ipfs://` and `ipns://` URLs.
- Uses all available methods to resolve a given CID to some content - it does not, for example, when given a subdomain gateway path, restrict downloading the blocks from only that subdomain gateway
> feat: support IPFS/IPNS paths, Gateways, etc

- packages/verified-fetch/README.md
- packages/verified-fetch/src/index.ts
- packages/verified-fetch/src/utils/responses.ts
- packages/verified-fetch/src/verified-fetch.ts
- packages/verified-fetch/test/verified-fetch.spec.ts
Adds support for simulating redirects for UnixFS directories.
We're somewhat in uncharted water here because `window.fetch` does this transparently unless you specify a [redirect option](https://developer.mozilla.org/en-US/docs/Web/API/fetch#redirect), none of which actually allow you to manually follow a redirect.
The states we can be in are:
1. URL: `ipfs://QmFoo/dir/`
- Happy path
- 200 response
- `response.redirected = false`
- `response.url = 'ipfs://QmFoo/dir'`
2: URL: `ipfs://QmFoo/dir`, `redirect: 'follow'`
- The default value
- Simulates automatically following a redirect
- 200 response
- `response.redirected = true`
- `response.url = 'ipfs://QmFoo/dir/'`
3: URL: `ipfs://QmFoo/dir`, `redirect: 'error'`
- Throw an error if a redirect would take place
- Throws `TypeError('Failed to …
> feat: support redirects for UnixFS directories

- packages/verified-fetch/test/verified-fetch.spec.ts
Adds tests to ensure gateway and subdomain gateways return redirects that are browser-cacheable.
Refs: https://github.com/ipfs-shipyard/helia-service-worker-gateway/issues/62#issuecomment-1981379184
> chore: add tests for directory redirects for gateways

- packages/verified-fetch/src/utils/parse-url-string.ts
- packages/verified-fetch/test/utils/parse-url-string.spec.ts
Feat: Support `https?://<dnsLink>.ipns.<domain>` URLs
helia-http-gateway and helia-service-worker-gateway can now pass any urls they receive directly to @helia/verfied-fetch without having to do any URL parsing.
> fix: support https?://<dnsLink>.ipns.<gateway> urls

- packages/verified-fetch/test/utils/parse-url-string.spec.ts
fixes the build.
When pulling down the latest changes on main, and running `npm run reset && npm i && npm run build` things failed to build due to incorrect stub type
> chore: fix build

- packages/interop/CHANGELOG.md
- packages/interop/package.json
- packages/verified-fetch/CHANGELOG.md
- packages/verified-fetch/package.json
- packages/verified-fetch/src/types.ts
- packages/verified-fetch/src/utils/byte-range-context.ts
- packages/verified-fetch/src/utils/get-stream-from-async-iterable.ts
- packages/verified-fetch/src/utils/parse-resource.ts
- packages/verified-fetch/src/utils/parse-url-string.ts
- packages/verified-fetch/src/utils/request-headers.ts
- packages/verified-fetch/src/utils/response-headers.ts
- packages/verified-fetch/src/utils/responses.ts
- packages/verified-fetch/src/verified-fetch.ts
- packages/verified-fetch/test/cache-control-header.spec.ts
- packages/verified-fetch/test/custom-dns-resolvers.spec.ts
- packages/verified-fetch/test/fixtures/ipns-stubs.ts
- packages/verified-fetch/test/range-requests.spec.ts
- packages/verified-fetch/test/utils/byte-range-context.spec.ts
- packages/verified-fetch/test/utils/parse-url-string.spec.ts
- packages/verified-fetch/test/utils/request-headers.spec.ts
- packages/verified-fetch/test/utils/response-headers.spec.ts
PR on top of https://github.com/ipfs/helia-verified-fetch/pull/19 implementing new DNS changes
> feat: implement new ipns record&answer properties

- packages/verified-fetch/src/utils/byte-range-context.ts
- packages/verified-fetch/src/utils/request-headers.ts
- packages/verified-fetch/src/utils/response-headers.ts
- packages/verified-fetch/test/range-requests.spec.ts
- packages/verified-fetch/test/utils/byte-range-context.spec.ts
- packages/verified-fetch/test/utils/request-headers.spec.ts
- packages/verified-fetch/test/utils/response-headers.spec.ts
- fix: request-headers byte range parsing
- fix: response-headers byte parsing
- fix: request-headers
- fix: byteRangeContext tests
- fix: range-requests tests
Fix byte range parsing
Byte range requests (`<range-start>-<range-end>/<size>`) should never be in a state where `<range-end>` is greater than or equal to `<size>`. This PR fixes the byte range parsing in the request and response headers to ensure that the range is always valid.
More info in https://github.com/ipfs-shipyard/helia-service-worker-gateway/pull/122#issuecomment-2005215744
> fix: byte range request end should never equal file size

- packages/verified-fetch/src/utils/get-stream-from-async-iterable.ts
- packages/verified-fetch/src/utils/parse-resource.ts
- packages/verified-fetch/src/utils/parse-url-string.ts
- packages/verified-fetch/src/utils/responses.ts
- packages/verified-fetch/src/verified-fetch.ts
- packages/verified-fetch/test/abort-handling.spec.ts
- packages/verified-fetch/test/cache-control-header.spec.ts
- packages/verified-fetch/test/custom-dns-resolvers.spec.ts
- packages/verified-fetch/test/fixtures/dns-answer-fake.ts
- packages/verified-fetch/test/fixtures/get-abortable-promise.ts
- packages/verified-fetch/test/fixtures/make-aborted-request.ts
feat: abort signals are respected
fixes https://github.com/ipfs/helia-verified-fetch/issues/25
need some eyes on this to ensure the approach is sound and that we're exiting as early as possible.
slightly WIP but I do need feedback, so PR not marked as WIP.
There was an obvious bug where signal was not being passed through fully. :
1. no signal being read at all (it was always undefined): see the changes to `convertOptions`
2. parse-resource did not previously accept a signal.
2. parse-url-string did not previously accept a signal.
I'm happy to revert some of the explicit signal handling and just get through the fixes to the above, but I think we should exit early when we can.
> feat: abort signals are respected

- packages/verified-fetch/README.md
- packages/verified-fetch/src/utils/get-stream-from-async-iterable.ts
- packages/verified-fetch/src/verified-fetch.ts
- packages/verified-fetch/test/abort-handling.spec.ts
fix: aborted signals throw libp2p AbortError
Fixes #25, specifically https://github.com/ipfs/helia-verified-fetch/issues/25#issuecomment-2014852934
* signal aborts throw `AbortError` from `@libp2p/interface` instead of returning a Response object
* Updated README.md to mention that this AbortError is not the typical DOMException AbortError thrown by native `fetch`
* updated the URL for not implemented codec requests to point to the correct repo
* added tests to ensure that aborts during `.stat` and `.cat` are handled correctly
N/A
> fix: aborted signals throw libp2p AbortError

- packages/verified-fetch/src/utils/parse-url-string.ts
- packages/verified-fetch/src/utils/tlru.ts
- packages/verified-fetch/test/cache-control-header.spec.ts
- packages/verified-fetch/test/utils/parse-url-string.spec.ts
This PR mainly fixes the TLRU cache behaviour by ensuring that when setting DNSLink and IPNS resolution answers to the cache, **we correctly convert the TTL from seconds to milliseconds as expected by the TLRU cache** 
In addition: 
- Adds tests to ensure that the correct TTL is returned by the `parseUrlString` function. 
- Converts the IPNS record TTL from nanoseconds to seconds correctly. 
- This should fix some of the duplicate resolutions reported in https://github.com/ipfs-shipyard/helia-service-worker-gateway/issues/59. However, it should 
- We still need to follow up in js-ipns regarding why [nanoseconds are incorrectly calculated](https://github.com/ipfs/js-ipns/blob/e933496d93e553662b968019b57a2f8413fbefc6/src/index.ts#L200) when converting from ms.
> fix: ttl and caching for ipns urls

- packages/verified-fetch/src/utils/parse-url-string.ts
- packages/verified-fetch/test/utils/parse-url-string.spec.ts
- packages/verified-fetch/test/verified-fetch.spec.ts
fix: decodeURIComponent on path parts
Fixes an issue where we were not properly handling encoded URI components in URLs.
fixes https://github.com/ipfs-shipyard/service-worker-gateway/issues/83
This PR is first submitted with failing src (TDD) tests to demonstrate the issue. Then the fix is applied and the tests are updated to pass.
```bash
> npx aegir test --build true --bail false
...
311 passing (357ms)
2 pending
2 failing
1) parseUrlString
/ipfs/<CID> URLs
can parse an IPFS path with encodedURIComponents:
AssertionError: expected 'I/Plan_d\'ex%C3%A9cution_du_second_%C…' to equal 'I/Plan_d\'exécution_du_second_étage_d…'
+ expected - actual
-I/Plan_d'ex%C3%A9cution_du_second_%C3%A9tage_de_l'h%C3%B4tel_de_Brionne_(dessin)_De_Cotte_2503c_%E2%80%93_Gallica_2011_(adjusted).jpg.webp …
```
> fix: decodeURIComponent on path parts

- packages/verified-fetch/src/verified-fetch.ts
The signal from this abort controller replaces any user-supplied signal in forward operations.
When the user supplied signal aborts we call abort on the abort controller, aborting it's signal.
We do not call `.abort()` on the abort controller for any other reason, therefore it can be removed and the user-supplied abort signal can be passed through unmodified.
The redundant abort controller's signal also has the default limit on the number of event listeners so it causes `"possible EventEmitter memory leak detected"` warnings in node which people frequently mistake for an error and file issues about.
This manifests itself in `helia-http-gateway` as:
```
(node:58297) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use …
```
> fix: remove redundant abort controller

- packages/verified-fetch/src/verified-fetch.ts
chore: pass url and body to badRequestResponse
fixes #27
Simple fix making sure we pass the resource and body to `badRequestResponse`.
> fix: pass url and body to badRequestResponse

- packages/verified-fetch/package.json
- packages/verified-fetch/src/verified-fetch.ts
- packages/verified-fetch/test/content-type-parser.spec.ts
- packages/verified-fetch/test/fixtures/create-offline-helia.ts
fix: identity CIDs use contentTypeParser
latest update of `@helia/verified-fetch` caused failing tests in service-worker-gateway: https://github.com/ipfs-shipyard/service-worker-gateway/pull/187
Fixes https://github.com/ipfs/helia-verified-fetch/issues/48
This change normalizes how we handle setting content-type for raw CIDs and identity CIDs and was required to ensure that the content-type is set correctly for identity CIDs.
> fix: identity CIDs use contentTypeParser

- packages/verified-fetch/src/verified-fetch.ts
- packages/verified-fetch/test/verified-fetch.spec.ts
Fixes #53
When initially writing the test for this, I discovered a bug when trying to create a dag-pb CID, reported as https://github.com/ipfs/helia/issues/506
> fix: missing paths returns 404 instead of 502

- .github/workflows/js-test-and-release.yml
The `pl-strflt` org has been renamed `ipdxco`, the `uci` repo has been renamed `unified-github-workflows` and someone deleted the `v0.0` tag so update to the new versions.
> chore: start running CI again

- packages/gateway-conformance/.aegir.js
- packages/gateway-conformance/package.json
- packages/gateway-conformance/src/conformance.spec.ts
- packages/gateway-conformance/src/demo-server.ts
- packages/gateway-conformance/src/fixtures/basic-server.ts
- packages/gateway-conformance/src/fixtures/content-type-parser.ts
- packages/gateway-conformance/src/fixtures/create-kubo.ts
- packages/gateway-conformance/src/fixtures/create-verified-fetch.ts
- packages/gateway-conformance/src/fixtures/kubo-mgmt.ts
- fix: fixture loading
- fix: bug with parsing certain content
fix: gateway conformance tests
Fixes https://github.com/ipfs/helia-verified-fetch/issues/79
Note: there are infinite loops occurring on some gateway conformance tests, and I have disabled them for now.
> fix: gateway conformance tests

- packages/gateway-conformance/src/conformance.spec.ts
changes gateway conformance tests to verify success percentage instead of count of success/failures, which should prevent regressions on individual test cases if new tests are added or somehow checking counts doesn't account for something we break.
e.g. https://github.com/ipfs/helia-verified-fetch/issues/82#issuecomment-2116132285
> test: use successRate for gateway conformance tests

- .github/workflows/gateway-conformance.yml
- packages/gateway-conformance/src/conformance.spec.ts
- packages/gateway-conformance/src/constants.ts
- packages/gateway-conformance/src/fixtures/kubo-mgmt.ts
This PR switches to v6 with changes from https://github.com/ipfs/gateway-conformance/pull/211
- `IPFS_NS_MAP` handling refactored: No need to generate env from `dnslink.json`, a fixture in desired format is already provided, and we no longer mix subdomains with DNSLink tests, which also simplifies code
> refactor: IPFS_NS_MAP from gateway-conformance v6

- packages/verified-fetch/src/index.ts
As discussed in person, this changes the default configuration to use the waterworks trustless gateway. 
This should increase retrieval success for users with the default config.
> feat: use the waterworks trustless gateway by default

- packages/verified-fetch/README.md
- packages/verified-fetch/src/index.ts
I'm just starting with IPFS, but I'm assuming it's not supposed to say "`cidv0` & `cidv0`"
> docs: change cidv0 to cidv1 in the readme

- packages/verified-fetch/src/verified-fetch.ts
- packages/verified-fetch/test/accept-header.spec.ts
feat: return IPNSRecords for ipns subdomain URLs
Adds the ability to get IPNS records given a fetch URL of `http://k51_something.ipns.example.com`
Fixes #29
My network gives issues when running tests, so I'm pushing this up hoping it will pass the tests on the CI.
> feat: return IPNSRecords for ipns subdomain URLs

- README.md
change from `https://ipfs.github.io/helia-verified-fetch/modules/` to `https://ipfs.github.io/helia-verified-fetch/modules/_helia_verified_fetch.html`
https://ipfs.github.io/helia-verified-fetch/modules/ give 404
- [] I have added tests that prove my fix is effective or that my feature works
> docs: api docs link in readme

- .github/dependabot.yml
chore: use grouping for dependabot
Attempting to modify dependabot so that dependencies that should be grouped are.. this aims to prevent a bunch of single dep update PRs that require other deps to be updated at the same time.
> chore: use grouping for dependabot

- packages/verified-fetch/src/utils/libp2p-defaults.browser.ts
We don't really need the bootstrap nodes for retrieval.
> fix: do not connect to bootstrap nodes in browsers

- packages/verified-fetch/src/index.ts
While testing different bundlers/CDNs it seemed like the browser overrides we define in package.json aren't always respected. This gives us a way to check this quickly.
> fix: add trace logging of libp2p config

- packages/verified-fetch/src/index.ts
- packages/verified-fetch/src/types.ts
- packages/verified-fetch/src/utils/set-content-type.ts
- packages/verified-fetch/src/utils/type-guards.ts
- packages/verified-fetch/src/utils/walk-path.ts
- packages/verified-fetch/src/verified-fetch.ts
refactor: move set-content-type function
Prepping for code changes for https://github.com/ipfs/helia-verified-fetch/issues/52
> refactor: move set-content-type function

- packages/gateway-conformance/src/conformance.spec.ts
test: gateway conformance failures are easier to debug
Makes it easier to debug gateway-conformance failures when a code change causes a test that was previously passing to fail.
While working on https://github.com/ipfs/helia-verified-fetch/pull/169, I ended up having to debug diffs of passing/failing gateway-conformance test outputs to figure out which exact check was failing. This PR makes it easier to debug such failures by printing the test output to the console when a test fails, and allowing us to specify which exact tests we expect to pass.
FYI, i got the names of the passing and failing tests by running:
```shell
DEBUG="gateway-conformance*,gateway-conformance*:trace" npm run test >& log.txt
DEBUG="gateway-conformance*,gateway-conformance*:trace" npm run test -- -g …
```
> test: gateway conformance failures are easier to debug

- packages/verified-fetch/src/plugins/plugin-handle-dag-pb.ts
- packages/verified-fetch/src/utils/dir-index-html.ts
- **fix: shortHash display**
- **fix: stop infinite redirects for directory subdomain requests**
- **fix: shorthash link works properly**
fix: shorthand url appears and links correctly
A few fixes here:
1. shorthash displays the same as on dweb.link and ipfs.io (e.g. `Qm12...HnzA`)
2. shorthash links to the correct URL (e.g. `https://${url.host}$/ipfs/Qm12...HnzA`)
3. stops infinite redirects for directory subdomain requests (i.e. `https://Qm12...HnzA.ipfs.${url.host}`) would previously infinitely redirect causing a 500 error.
Fixes #180
> fix: shorthand url appears and links correctly

- packages/verified-fetch/src/utils/byte-range-context.ts
- packages/verified-fetch/test/utils/byte-range-context.spec.ts
fix: byte-range request body size
Fixes https://github.com/ipfs/helia-verified-fetch/issues/184
> fix: byte-range request body size

- packages/gateway-conformance/src/conformance.spec.ts
Fix the way the go bin path is constructed if GOPATH is set. Make sure we also add `bin` to the path, because binaries live in the `$GOPATH/bin`.
See https://go.dev/wiki/GOPATH
> fix: go bin path

- packages/verified-fetch/src/plugins/types.ts
- packages/verified-fetch/src/verified-fetch.ts
- packages/verified-fetch/test/get-e-tag.spec.ts
fix: etag is path aware
Update plugin types & make work with `handleFinaleResponse`, clean up `fetch` impl internals, add get-e-tag test to verify path-awareness.
Fixes #196
> fix: etag is path aware

- packages/verified-fetch/src/utils/dir-index-html.ts
fix: dir-index-html shorthash links correctly
Strips the subdomain for short-hash link clicks. Mimics what dweb.link dir-index-html does.
Fixes https://github.com/ipfs/service-worker-gateway/issues/639
> fix: dir-index-html shorthash links correctly
